import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
      <nav>
          <div className='main-nav'>
            <div className='logo'>
              <Link href="/"><h3>Next App</h3></Link>
            </div>
            <div className='inside-main-nav'>
              <div><Link href="/">Home</Link></div>
              <div><Link href="/about">About</Link></div>
              <div><Link href="/login">Login</Link></div>
              <div><Link href="/studentlist">Students list</Link></div>
            </div>
          </div>
        </nav>
        <div className='children'>
        {children}
        </div>
      </body>
    </html>
  )
}
